Custom rest_client_options via Conjur configuration
cyberark/conjur-api-ruby pull request #189
Opened 2021-04-29 12:02 UTC by doodlesbykumbi

### What does this PR do?

This replaces the monkey patch to RestClient::Request that made it always uses :ssl_cert_store, which polluted into usage of RestClient outside the scope of Conjur. The new approach provides a sane default that retains the previous behavior, and gives the user the ability to configure RestClient::Requests scoped only to Conjur.

### What ticket does this PR close?
Connected to https://github.com/cyberark/conjur-api-ruby/issues/188

### Checklists

#### Change log
- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [x] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [x] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

2021-04-29 13:32 UTC, fmang commented
That does the trick for me. I checked that the previous approach with `OpenSSL::SSL::SSLContext::DEFAULT_CERT_STORE.add_file` still works, and that the new approach with `Conjur.configuration.rest_client_options = { ssl_ca_file: 'my_cert.crt' }` works too. I also checked with a proxy.

Thank you !

2021-04-29 22:06 UTC, diverdane reviewed
Certainly LGTM, but could probably use a review by someone more familiar with this code.

2021-05-03 14:27 UTC, jtuttle requested changes
Functionality seems fine, just some style requests.

2021-05-03 14:27 UTC, jtuttle commented on CHANGELOG.md
> +- Replaces monkey patching RestClient::Request, to always set :ssl_cert_store,
Can we shorten this CHANGELOG entry a bit? Something like "Remove RestClient::Request monkeypatch to allow configuration of :ssl_cert_store to be scoped to Conjur".

2021-05-03 14:27 UTC, jtuttle commented on README.md
> +Conjur.configuration.rest_client_options = {
Can you add a blurb about why we have to do this? Is it required?

2021-05-03 14:27 UTC, jtuttle commented on lib/conjur/api/router/v4.rb
> +          RestClient::Resource.new(Conjur.configuration.authn_url, Conjur.configuration.rest_client_options.merge(user: username, password: password))['users/login']
Please break this line up and maybe add a helper variable for `Conjur.configuration.rest_client_options.merge(...)`

2021-05-03 14:27 UTC, jtuttle commented on lib/conjur/api/router/v4.rb
> +          RestClient::Resource.new(Conjur.configuration.authn_url, Conjur.configuration.rest_client_options)['users'][fully_escape username]['authenticate']
Again please break this line up.

2021-05-03 14:27 UTC, jtuttle commented on lib/conjur/api/router/v4.rb
> +          RestClient::Resource.new(Conjur.configuration.authn_url, Conjur.configuration.rest_client_options.merge(credentials || {}))['users']["api_key?id=#{username}"]
Please break this line up too.

2021-05-03 14:27 UTC, jtuttle commented on lib/conjur/api/router/v4.rb
> +          RestClient::Resource.new(Conjur.configuration.core_url, Conjur.configuration.rest_client_options.merge(credentials || {}))['host_factories'][id.identifier]['tokens']
Can we make a helper method for `Conjur.configuration.rest_client_options.merge(credentials || {})`? Looks like it's repeated a bunch.

2021-05-03 14:27 UTC, jtuttle commented on lib/conjur/api/router/v5.rb
> +          RestClient::Resource.new(Conjur.configuration.authn_url, Conjur.configuration.rest_client_options.merge(user: username, password: password))[fully_escape account]['login']
Please apply helper methods and breaking-up-lines liberally to this file. :)

2021-05-03 14:27 UTC, jtuttle commented on spec/ssl_spec.rb
> +      cert_store.add_cert cert
Add parens for method call `add_cert(cert)`

2021-05-03 14:27 UTC, jtuttle commented on spec/configuration_spec.rb
> +      expect(configuration.rest_client_options).to eq expected
Add parens for method call: `eq(expected)`

2021-05-03 14:27 UTC, jtuttle commented on spec/configuration_spec.rb
> +      expect(resource.options).to include expected
Add parens for method call: `include(expected)`

2021-05-04 13:49 UTC, jtuttle commented on lib/conjur/api/router/v4.rb
> +                       id.identifier
I believe you can fix this slew of warnings by bumping the conditional onto the next line:

```
username =
  if id.kind ...
```

2021-05-04 13:51 UTC, jtuttle submitted a review, later dismissed
Looks good, just a few easy (I think) codeclimate warnings to address.

2021-05-04 17:39 UTC, jtuttle approved these changes

2021-05-04 21:14 UTC, merged